domain: "lapidooo.com"
url: "https://lapidooo.com"
title: "lapidooo"
description: " "
theme: jekyll-theme-cayman
google_analytics: UA-55798049-1
gems:
  - jekyll-sitemap
show_downloads: false
github:
  is_project_page: true
  zip_url: ""
  tar_url: ""
